### ISSUE TITLE
Provide better example

### ISSUE THREAD

**Issue by biklas7** [alfonsocejudo/fluster#1]
If you could provide a real-world example with flutter and the google maps plugin, it would be great.

**Comment by alfonsocejudo** [comment]
Hi @biklas7 have you already checked out this demo project: https://github.com/alfonsocejudo/fluster_demo

There's also this companion article: https://medium.com/jet-set-digital/map-marker-clustering-flutter-ft-google-maps-fluster-e9fe4e2c503b

Let me know if you've already seen these and still would like additional help with implementation, thanks!

**Comment by biklas7** [comment]
Hi @alfonsocejudo! Yes I saw that repo and got it working in my project. Thanks, it works really well! Have tried many packages and none worked like this one with Google maps. It's a shame that this package is not so popular. As a suggestion, maybe you could add that demo project to the example folder of this package and improve it a bit along with the readme instructions in order to be easier to understand your package for first time users. Thanks a lot.
