### ISSUE TITLE
Is there way to user mapbox with fluster

### ISSUE THREAD

**Issue by MATTYGILO** [alfonsocejudo/fluster#2]
Is there a way in which to use fluster with mapbox flutter 
https://pub.dev/packages/mapbox_gl#-readme-tab-

**Comment by alfonsocejudo** [comment]
Hi @MATTYGILO I've never implemented Mapbox before, have you taken a look at this clustering solution: https://github.com/lpongetti/flutter_map_marker_cluster

If that doesn't help with your use case at all, I can try making a quick demo project to see if mapbox_gl and fluster can work together, thanks!

**Comment by szybki8562** [comment]
Works with MapBox

**Comment by PaoloP98** [comment]
Could you share an example please?

**Comment by szybki8562** [comment]
Adding a fluster as in the description. 

example code is from my app

`Future<void> _addSymbolsFromClusters() async {
    symbols.clear();
    symbolsIds.clear();
    clusters.clear();
    clustersIds.clear();
    var bbox = await _mapController.getVisibleRegion();
    for (var itm in fluster.clusters([
      bbox.southwest.longitude,
      bbox.southwest.latitude,
      bbox.northeast.longitude,
      bbox.northeast.latitude
    ],
        _mapController.cameraPosition.zoom.toInt())) {
      if (itm.isCluster == false) {
          var so = SymbolOptions(
              geometry:
              LatLng(itm.latitude, itm.longitude),
              iconImage: 'marker',
              iconSize: itm.iconSize,
              draggable: false,
              iconRotate: itm.iconRotate,
              iconOpacity: 1
          );
          symbols.add(so);
          symbolsIds.putIfAbsent('IDs', () => itm.markerId);
      }
      else {
          var so = SymbolOptions(
            geometry:
            LatLng(itm.latitude, itm.longitude),
            iconImage: 'cluster',
            iconSize: itm.iconSize,
            draggable: false,
            iconRotate: itm.iconRotate,
              iconOpacity: 1
          );
          clusters.add(so);
          clustersIds.putIfAbsent('IDs', () => 'cluster' + itm.clusterId.toString());
      }
    }
  }`

isCameraMoving

`await _addSymbolsFromClusters();
 await _mapController.addSymbols(symbols, [symbolsIds]);
 await _mapController.addSymbols(clusters, [clustersIds]);`
