### ISSUE TITLE
Indeterministic behaviour over runs at constant zoom level

### ISSUE THREAD

**Issue by theochampion** [alfonsocejudo/fluster#3]
Hi there!

I'm using supercluster to cluster points in realtime on my client (generating cluster only at the zoom level I currently am) but I noticed something weird.
When the viewport change, I re fetch my points and re run the clustering on them, the resulting clusters are arranged differently (as shown below) than before even tho the points and zoom level is the same.

![ss](https://user-images.githubusercontent.com/14275989/65712418-498a6180-e097-11e9-935b-7c9b8009c68f.gif)

Is this normal behavior?

Cheers!

**Comment by alfonsocejudo** [comment]
Hey @theochampion thanks for taking the time to demonstrate this behavior. I'll do some investigating and get back to you when I can. Thanks again.

**Comment by theochampion** [comment]
Turn out to be specific to the supercluster algorithm itself. Supercluster implements a greedy clustering algorithm, meaning that order of input matters. Thus ensuring the input is ordered create deterministic results ;)

**Comment by alfonsocejudo** [comment]
Ah good to know, well done looking into it @theochampion
