### ISSUE TITLE
Get the location names of the markers in a cluster

### ISSUE THREAD

**Issue by MATTYGILO** [alfonsocejudo/fluster#5]
I was wondering if there is a way in which i can get all the cluster names/ids of the markers that make up a cluster.

Thanks for any suggestions or help?

**Comment by arthurdenner** [comment]
Hi @MATTYGILO! 👋

I'm not sure if I understand your question, but this library provides two methods: `children` and `points`. You can see them [here](https://github.com/alfonsocejudo/fluster#get-the-cluster-children).

In my case (using Flutter), I needed to access some extra information about each point inside a cluster, so I created a class that extended `Clusterable` and added the properties I needed and they were available on the results from `Fluster.points(clusterId)`.

The description above may be confusing, so read [this article](https://coletiv.com/blog/customize-your-cluster-markers-on-flutter-google-maps) for a better understanding - check the section `Implementing Fluster`.

**Comment by alfonsocejudo** [comment]
Thanks for helping out with this issue @arthurdenner

**Comment by arthurdenner** [comment]
@alfonsocejudo, can this issue be closed?
